[package]
name = "abacus_os"
version = "0.1.0"
authors = ["Connor Macdonald <csm119@uclive.ac.nz>"]
edition = "2018"

# See more keys and their definitions at https://doc.rust-lang.org/cargo/reference/manifest.html

[dependencies]
