[unstable]
build-std = ["core", "compiler_builtins"] # Forces rust to recompile core for our custom target
build-std-features = ["compiler-builtins-mem"] # Enables rust to use its own builtin-mem functions

[build]
target = "x86-64-abacus_os.json"